queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>1"
      - base=main
      - label=A:automerge
    merge_conditions:
      - "#approved-reviews-by>1"
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body }}
    merge_method: squash

pull_request_rules:
  - name: backport patches to v0.46.x branch
    conditions:
      - base=main
      - label=backport/0.46.x
    actions:
      backport:
        branches:
          - release/v0.46.x
  - name: backport patches to v0.45.x branch
    conditions:
      - base=main
      - label=backport/0.45.x
    actions:
      backport:
        branches:
          - release/v0.45.x
  - name: backport patches to v0.44.x branch
    conditions:
      - base=main
      - label=backport/0.44.x
    actions:
      backport:
        branches:
          - release/v0.44.x
  - name: backport patches to v0.42.x branch
    conditions:
      - base=main
      - label=backport/0.42.x (Stargate)
    actions:
      backport:
        branches:
          - release/v0.42.x
  - name: automerge to main with label automerge and branch protection passing
    conditions: []
    actions:
      queue:
